;;; oblique-strategies-ed5 --- Oblique Strategies.                    -*- lexical-binding: t; -*-

;; The list is a bit different form the site
;; https://gist.github.com/no-defun-allowed/068bb95c476201f009fcfeb135f21432
;; The cards were from http://www.rtqe.net/ObliqueStrategies/Ed5.html.
;; However, the sits has been gone since 2024 at least.

(defvar *oblique-strategy-list-ed5*
  '("Abandon normal instruments"
    "Accept advice"
    "Accretion"
    "Allow an easement (an easement is the abandonment of a stricture)"
    "Always first steps"
    "Are there sections? Consider transitions"
    "Ask people to work against their better judgement"
    "Ask your body"
    "Be dirty"
    "Be extravagant"
    "Be less critical more often"
    "Breathe more deeply"
    "Change nothing and continue with immaculate consistency"
    "Courage!"
    "Cut a vital connection"
    "Decorate, decorate"
    "Define an area as 'safe' and use it as an anchor"
    "Destroy -nothing -the most important thing"
    "Discard an axiom"
    "Disciplined self-indulgence"
    "Disconnect from desire"
    "Discover the recipes you are using and abandon them"
    "Distorting time"
    "Do nothing for as long as possible"
    "Do something boring"
    "Do the words need changing?"
    "Do we need holes?"
    "Don't be afraid of things because they're easy to do"
    "Don't be frightened of cliches"
    "Don't be frightened to display your talents"
    "Don't break the silence"
    "Don't stress one thing more than another"
    "Emphasise differences"
    "Emphasise the flaws"
    "Faced with a choice do both (given by Diter Rot)"
    "Gardening, not architecture"
    "Give the game away"
    "Give way to your worst impulse"
    "Go outside. Shut the door"
    "Go to an extreme, move back to a more comfortable place"
    "Honour thy error as a hidden intention"
    "How would you have done it?"
    "Humanise something free of error"
    "In total darkness or in a very large room, very quietly"
    "Is it finished?"
    "Is there something missing?"
    "Just carry on"
    "Listen to the quiet voice"
    "Look at the order in which you do things"
    "Look closely at the most embarrassing details and amplify them"
    "Make a blank valuable by putting it in an exquisite frame"
    "Make a sudden, destructive unpredictable action; incorporate"
    "Make an exhaustive list of everything you might do and do the last thing on the list"
    "Make it more sensual"
    "Make something implied more definite (reinforce, duplicate)"
    "Not building a wall but making a brick"
    "Once the search is in progress, something will be found"
    "Only a part, not the whole"
    "Only one element of each kind"
    "Overtly resist change"
    "Question the heroic approach"
    "Remember .those quiet evenings"
    "Remove ambiguities and convert to specifics"
    "Remove specifics and convert to ambiguities"
    "Repetition is a form of change"
    "Retrace your steps"
    "Reverse"
    "Short circuit (example; a man eating peas with the idea that they will improve his virility shovels them straight into his lap)"
    "Simple subtraction"
    "Simply a matter of work"
    "Slow preparation..Fast execution"
    "State the problem in words as clearly as possible"
    "Take a break"
    "Take away the elements in order of apparent non importance"
    "The inconsistency principle"
    "The most important thing is the thing most easily forgotten"
    "Think -inside the work -outside the work"
    "Tidy up"
    "Towards the insignificant"
    "Trust in the you of now"
    "Try faking it! (given by Stewart Brand)"
    "Turn it upside down"
    "Use 'unqualified' people"
    "Use an old idea"
    "Use an unacceptable colour"
    "Use filters"
    "Voice nagging suspicions"
    "Water"
    "What are you really thinking about just now? Incorporate"
    "What mistakes did you make last time?"
    "What to increase? What to reduce?"
    "What to maintain?"
    "What would your closest friend do?"
    "What wouldn't you do?"
    "When is it for?"
    "Where's the edge? Where does the frame start?"
    "Which elements can be grouped?"
    "Which frame would make this look right?"
    "Who should be doing this job? How would they do it?"
    "Work at a different speed"
    "Would anybody want it?"
    "You are an engineer"
    "You don't have to be ashamed of using your own ideas")
  "Oblique Strategies cards created by Brian Eno and Peter Schmidt.")

;;;###autoload
(defun oblique-strategies-ed5 ()
  "Show a message from Oblique Strategies cards Ed5."
  (interactive)
  (message "%s"
           (nth
            (random (length *oblique-strategy-list-ed5*))
            *oblique-strategy-list-ed5*)))

(defvar *oblique-strategy-list-ed5+*'("Abandon normal instruments"
                                      "Accept advice"
                                      "Accretion"
                                      "A line has two sides"
                                      "Allow an easement (an easement is the abandonment of a stricture)"
                                      "Are there sections? Consider transitions"
                                      "Ask people to work against their better judgment"
                                      "Ask your body"
                                      "Assemble some of the instruments in a group and treat the group"
                                      "Balance the consistency principle with the inconsistency principle"
                                      "Be dirty"
                                      "Breathe more deeply"
                                      "Bridges -build -burn"
                                      "Cascades"
                                      "Change instrument roles"
                                      "Change nothing and continue with immaculate consistency"
                                      "Children's voices -speaking -singing"
                                      "Cluster analysis"
                                      "Consider different fading systems"
                                      "Consult other sources -promising -unpromising"
                                      "Convert a melodic element into a rhythmic element"
                                      "Courage!"
                                      "Cut a vital connection"
                                      "Decorate, decorate"
                                      "Define an area as `safe' and use it as an anchor"
                                      "Destroy -nothing -the most important thing"
                                      "Discard an axiom"
                                      "Disconnect from desire"
                                      "Discover the recipes you are using and abandon them"
                                      "Distorting time"
                                      "Do nothing for as long as possible"
                                      "Don't be afraid of things because they're easy to do"
                                      "Don't be frightened of cliches"
                                      "Don't be frightened to display your talents"
                                      "Don't break the silence"
                                      "Don't stress one thing more than another"
                                      "Do something boring"
                                      "Do the washing up"
                                      "Do the words need changing?"
                                      "Do we need holes?"
                                      "Emphasize differences"
                                      "Emphasize repetitions"
                                      "Emphasize the flaws"
                                      "Faced with a choice, do both (given by Dieter Roth)"
                                      "Feedback recordings into an acoustic situation"
                                      "Fill every beat with something"
                                      "Get your neck massaged"
                                      "Ghost echoes"
                                      "Give the game away"
                                      "Give way to your worst impulse"
                                      "Go slowly all the way round the outside"
                                      "Honor thy error as a hidden intention"
                                      "How would you have done it?"
                                      "Humanize something free of error"
                                      "Imagine the music as a moving chain or caterpillar"
                                      "Imagine the music as a set of disconnected events"
                                      "Infinitesimal gradations"
                                      "Intentions -credibility of -nobility of -humility of"
                                      "Into the impossible"
                                      "Is it finished?"
                                      "Is there something missing?"
                                      "Is the tuning appropriate?"
                                      "Just carry on"
                                      "Left channel, right channel, center channel"
                                      "Listen in total darkness, or in a very large room, very quietly"
                                      "Listen to the quiet voice"
                                      "Look at a very small object; look at its center"
                                      "Look at the order in which you do things"
                                      "Look closely at the most embarrassing details and amplify them"
                                      "Lowest common denominator check -single beat -single note -single"
                                      "riff"
                                      "Make a blank valuable by putting it in an exquisite frame"
                                      "Make an exhaustive list of everything you might do and do the last"
                                      "thing on the list"
                                      "Make a sudden, destructive, unpredictable action; incorporate"
                                      "Mechanicalize something idiosyncratic"
                                      "Mute and continue"
                                      "Only one element of each kind"
                                      "(Organic) machinery"
                                      "Overtly resist change"
                                      "Put in earplugs"
                                      "Remember those quiet evenings"
                                      "Remove ambiguities and convert to specifics"
                                      "Remove specifics and convert to ambiguities"
                                      "Repetition is a form of change"
                                      "Reverse"
                                      "Short circuit"
                                      "improve his virility shovels them straight into his lap)"
                                      "Shut the door and listen from outside"
                                      "Simple subtraction"
                                      "Spectrum analysis"
                                      "Take a break"
                                      "Take away the elements in order of apparent non-importance"
                                      "Tape your mouth (given by Ritva Saarikko)"
                                      "The inconsistency principle"
                                      "The tape is now the music"
                                      "Think of the radio"
                                      "Tidy up"
                                      "Trust in the you of now"
                                      "Turn it upside down"
                                      "Twist the spine"
                                      "Use an old idea"
                                      "Use an unacceptable color"
                                      "Use fewer notes"
                                      "Use filters"
                                      "Use "unqualified" people"
                                      "Water"
                                      "What are you really thinking about just now? Incorporate"
                                      "What is the reality of the situation?"
                                      "What mistakes did you make last time?"
                                      "What would your closest friend do?"
                                      "What wouldn't you do?"
                                      "Work at a different speed"
                                      "You are an engineer"
                                      "You can only make one dot at a time"
                                      "You don't have to be ashamed of using your own ideas")
  "List of All Oblique Strategies cited from
https://blog.matt-rickard.com/p/list-of-all-oblique-strategies
2022-05-24.")

;;;###autoload
(defun oblique-strategies-ed5+ ()
  "Show a message from Oblique Strategies cards Ed5."
  (interactive)
  (message "%s"
           (nth
            (random (length *oblique-strategy-list-ed5+*))
            *oblique-strategy-list-ed5+*)))

(provide 'oblique-strategies-ed5)
